### ISSUE TITLE
Compile error with 0.6.1

### ISSUE THREAD

**Issue by martinellison** [Boscop/web-view#150] opened 2020-03-14 09:23 UTC
I'm getting a compile error:

>    Compiling web-view v0.6.1
> error[E0432]: unresolved imports `ffi::DialogFlags`, `ffi::DialogType`
>  --> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/web-view-0.6.1/src/dialog.rs:1:17
>   |
> 1 | use ffi::{self, DialogFlags, DialogType};
>   |                 ^^^^^^^^^^^  ^^^^^^^^^^ no `DialogType` in the root
>   |                 |
>   |                 no `DialogFlags` in the root
> 
> error[E0425]: cannot find function `webview_dialog` in crate `ffi`
>   --> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/web-view-0.6.1/src/dialog.rs:32:18
>    |
> 32 |             ffi::webview_dialog(
>    |                  ^^^^^^^^^^^^^^ help: a function with a similar name exists: `webview_eval`
>    | 
>   :::

**Comment by martinellison** [comment] 2020-03-14 11:11
Using the following in `Cargo.toml` makes it build:

> #web-view = "0.6.0"
> web-view = { git = "https://github.com/Boscop/web-view" }

**Comment by not-matthias** [comment] 2020-03-14 14:14
The issue is in the `webview-sys` crate. You can manually downgrade the version from `v0.4.2` to `v0.4.1`: 
```
cargo update -p webview-sys --precise 0.4.1
```

**Comment by zxey** [comment] 2020-03-15 00:44
Sorry about that, published new version 0.6.2 where it should be fixed.

**Closed by zxey** 2020-03-15 00:44 UTC
