### ISSUE TITLE
need set CC=cl when build with i686-msvc

### ISSUE THREAD

**Issue by ghost** [Boscop/web-view#3] opened 2018-01-22 18:01 UTC
CC=cl cargo build --example timer

**Comment by Boscop** [comment] 2018-01-22 23:18
Thanks for the report. 
I can't reproduce on Windows.
Which OS are you running this on?
And what is the error when it crashes?

**Comment by Boscop** [comment] 2018-01-22 23:31
Ah, I can reproduce it now, it happens in `webview_terminate()`:

![image](https://user-images.githubusercontent.com/535593/35249961-809d58f8-ffd4-11e7-9e86-42c0080c9db0.png)

![image](https://user-images.githubusercontent.com/535593/35249926-4ad8441c-ffd4-11e7-8a24-2fbf94765a05.png)

At the time of the crash, on the console it already rendered/printed the state once: 
`counter: 1, userdata: -1`

**Comment by Boscop** [comment] 2018-01-22 23:42
It seems the other examples also crash the same way when built with i686-msvc in release mode..

**Comment by Boscop** [comment] 2018-01-25 12:25
Why did you close this? :confused:

**Comment by Freaky** [comment] 2019-05-15 18:16
It appears the invoke callbacks are defined using the wrong calling convention.  Changing `extern "system"` to `extern "C"` makes my 32bit builds work.

**Comment by Freaky** [comment] 2019-05-15 23:24
Windows devs might also be interested in my [various-fixes branch](https://github.com/Freaky/webview/tree/various-fixes) of webview, which plugs some memory leaks, fixes dialog(), and makes sure the event loop doesn't try processing an uninitialized message.

Most of these already have PRs that are going nowhere, so not likely to bother submitting upstream.  I think the leak fixes are novel, but, eh.

**Comment by zxey** [comment] 2019-09-05 19:36
This should now be fixed.

**Closed by zxey** 2019-09-05 19:36 UTC
Labels: bug, help wanted
